<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <RootNamespace>LiteMon.Wpf</RootNamespace>
    <AssemblyName>LiteMon</AssemblyName>
    <Version>0.2.0</Version>
    <SatelliteResourceLanguages>zh-Hans;en</SatelliteResourceLanguages>
    <!-- 内存优化：工作站并发 GC + 堆上限 -->
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <RetainVMGarbageCollection>false</RetainVMGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.GC.HeapHardLimit" Value="0x2000000" Trim="true" /> <!-- 32MB -->
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LiteMon.Core\LiteMon.Core.csproj" />
  </ItemGroup>

</Project>
